version: '2'

services:

  gateway-config:
    image: radicale/hm-config:c48d03a
    depends_on:
      - dbus-session
      - diagnostics
    environment:
      - FIRMWARE_VERSION=2022.05.19.0
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - miner-storage:/var/data
      - dbus:/session/dbus
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.kernel-modules: 1
      io.balena.features.dbus: 1
    stop_signal: SIGINT

  packet-forwarder:
    image: radicale/hm-pktfwd:b3af42a
    depends_on:
      - helium-miner
    restart: always
    privileged: true
    volumes:
      - pktfwdr:/var/pktfwd

  helium-miner:
    image: radicale/hm-miner:arm64-99375cc
    depends_on:
      - dbus-session
      - diagnostics
    expose:
      - "1680"
      - "4467"
    ports:
      - "44158:44158/tcp"
    volumes:
      - miner-storage:/var/data
      - miner-log:/var/log/miner
      - pktfwdr:/var/pktfwd
      - dbus:/session/dbus
    cap_add:
      - SYS_RAWIO
    devices:
    # TODO: Should be miner agnostic
      - /dev/i2c-0:/dev/i2c-0
    restart: on-failure
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
      - RELEASE_BUMPER=foobar

  diagnostics:
    image: radicale/hm-diag:5981ab0
    environment:
      - FIRMWARE_VERSION=2022.05.19.0
      - DIAGNOSTICS_VERSION=a3fd21c
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    volumes:
      - pktfwdr:/var/pktfwd
      - miner-storage:/var/data
    ports:
      - "80:5000"
    cap_add:
      - SYS_RAWIO
    devices:
    # TODO: Should be miner agnostic
      - /dev/i2c-0:/dev/i2c-0
    privileged: true
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.procfs: 1
      io.balena.features.dbus: 1

  # upnp:
  #   image: nebraltd/hm-upnp:b575a2f
  #   network_mode: host
  #   restart: on-failure
  #   volumes:
  #     - pktfwdr:/var/pktfwd

  dbus-session:
    image: balenablocks/dbus:rpi-0.0.2
    restart: always
    volumes:
      - dbus:/session/dbus
    environment:
      - DBUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
      - FIRMWARE_VERSION=2022.05.19.0

  wireguard:
    image: radicale/hm-wg:latest
    privileged: true
    network_mode: host
    labels:
      io.balena.features.kernel-modules: 1

volumes:
  miner-storage:
  miner-log:
  pktfwdr:
  dbus:
