name: BalenaCloud Deploy (Testnet - Draft Deploy)

on:
  workflow_dispatch:

jobs:
  testnet:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Random sleep (balena API workaround)
        run:  sleep $[ ( $RANDOM % 180 )  + 1 ]s
      - name: Balena Deploy (RasPi)
        uses: nebraltd/balena-cli-action@v12.54.5
        if: success()
        with:
          balena_api_token: ${{secrets.BALENA_API_TOKEN}}
          balena_command: "deploy radicale/helium-testnet --logs --debug --nocache --build --draft"
